//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISSUE
    {
        public int ISSUE_ID { get; set; }
        public string STUDENT_NAME { get; set; }
        public int SEMESTER { get; set; }
        public string BOOK_NAME { get; set; }
        public string ISSUE_DATE { get; set; }
        public string RETURN_DATE { get; set; }
    }
}
