//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSample.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class managementEntities : DbContext
    {
        public managementEntities()
            : base("name=managementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ISSUE> ISSUEs { get; set; }
        public virtual DbSet<TBL_BREGISTER> TBL_BREGISTER { get; set; }
        public virtual DbSet<TBL_COUNTBOOK> TBL_COUNTBOOK { get; set; }
        public virtual DbSet<TBL_PUBLISHER> TBL_PUBLISHER { get; set; }
        public virtual DbSet<TBL_SIGNUP> TBL_SIGNUP { get; set; }
        public virtual DbSet<TBL_SREGISTER> TBL_SREGISTER { get; set; }
    
        public virtual int P_REGISTER(string p_BOOK_NAME, string p_AUTHOR_NAME, string p_PUBLISHER_NAME, string p_EDITION, Nullable<int> p_SEMESTER, Nullable<int> p_NUMBER_OF_COPIES, string p_IMAGE, ObjectParameter v_OUT)
        {
            var p_BOOK_NAMEParameter = p_BOOK_NAME != null ?
                new ObjectParameter("P_BOOK_NAME", p_BOOK_NAME) :
                new ObjectParameter("P_BOOK_NAME", typeof(string));
    
            var p_AUTHOR_NAMEParameter = p_AUTHOR_NAME != null ?
                new ObjectParameter("P_AUTHOR_NAME", p_AUTHOR_NAME) :
                new ObjectParameter("P_AUTHOR_NAME", typeof(string));
    
            var p_PUBLISHER_NAMEParameter = p_PUBLISHER_NAME != null ?
                new ObjectParameter("P_PUBLISHER_NAME", p_PUBLISHER_NAME) :
                new ObjectParameter("P_PUBLISHER_NAME", typeof(string));
    
            var p_EDITIONParameter = p_EDITION != null ?
                new ObjectParameter("P_EDITION", p_EDITION) :
                new ObjectParameter("P_EDITION", typeof(string));
    
            var p_SEMESTERParameter = p_SEMESTER.HasValue ?
                new ObjectParameter("P_SEMESTER", p_SEMESTER) :
                new ObjectParameter("P_SEMESTER", typeof(int));
    
            var p_NUMBER_OF_COPIESParameter = p_NUMBER_OF_COPIES.HasValue ?
                new ObjectParameter("P_NUMBER_OF_COPIES", p_NUMBER_OF_COPIES) :
                new ObjectParameter("P_NUMBER_OF_COPIES", typeof(int));
    
            var p_IMAGEParameter = p_IMAGE != null ?
                new ObjectParameter("P_IMAGE", p_IMAGE) :
                new ObjectParameter("P_IMAGE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_REGISTER", p_BOOK_NAMEParameter, p_AUTHOR_NAMEParameter, p_PUBLISHER_NAMEParameter, p_EDITIONParameter, p_SEMESTERParameter, p_NUMBER_OF_COPIESParameter, p_IMAGEParameter, v_OUT);
        }
    
        public virtual ObjectResult<P_GET_REGISTER_Result> P_GET_REGISTER()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_GET_REGISTER_Result>("P_GET_REGISTER");
        }
    
        public virtual int P_STUDENT(string p_FIRST_NAME, string p_ADDRESS, string p_DATEOFBIRTH, string p_PHONE, Nullable<int> p_AGE, string p_GENDER, Nullable<int> p_SEM, string p_IMAGE, ObjectParameter v_OUT)
        {
            var p_FIRST_NAMEParameter = p_FIRST_NAME != null ?
                new ObjectParameter("P_FIRST_NAME", p_FIRST_NAME) :
                new ObjectParameter("P_FIRST_NAME", typeof(string));
    
            var p_ADDRESSParameter = p_ADDRESS != null ?
                new ObjectParameter("P_ADDRESS", p_ADDRESS) :
                new ObjectParameter("P_ADDRESS", typeof(string));
    
            var p_DATEOFBIRTHParameter = p_DATEOFBIRTH != null ?
                new ObjectParameter("P_DATEOFBIRTH", p_DATEOFBIRTH) :
                new ObjectParameter("P_DATEOFBIRTH", typeof(string));
    
            var p_PHONEParameter = p_PHONE != null ?
                new ObjectParameter("P_PHONE", p_PHONE) :
                new ObjectParameter("P_PHONE", typeof(string));
    
            var p_AGEParameter = p_AGE.HasValue ?
                new ObjectParameter("P_AGE", p_AGE) :
                new ObjectParameter("P_AGE", typeof(int));
    
            var p_GENDERParameter = p_GENDER != null ?
                new ObjectParameter("P_GENDER", p_GENDER) :
                new ObjectParameter("P_GENDER", typeof(string));
    
            var p_SEMParameter = p_SEM.HasValue ?
                new ObjectParameter("P_SEM", p_SEM) :
                new ObjectParameter("P_SEM", typeof(int));
    
            var p_IMAGEParameter = p_IMAGE != null ?
                new ObjectParameter("P_IMAGE", p_IMAGE) :
                new ObjectParameter("P_IMAGE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_STUDENT", p_FIRST_NAMEParameter, p_ADDRESSParameter, p_DATEOFBIRTHParameter, p_PHONEParameter, p_AGEParameter, p_GENDERParameter, p_SEMParameter, p_IMAGEParameter, v_OUT);
        }
    
        public virtual ObjectResult<P_GET_STUDENT_Result> P_GET_STUDENT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_GET_STUDENT_Result>("P_GET_STUDENT");
        }
    
        public virtual ObjectResult<P_GET_PUBLISHER_Result> P_GET_PUBLISHER()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_GET_PUBLISHER_Result>("P_GET_PUBLISHER");
        }
    
        public virtual int P_PUBLISHER(string p_PUBLISHER_NAME, ObjectParameter v_OUT)
        {
            var p_PUBLISHER_NAMEParameter = p_PUBLISHER_NAME != null ?
                new ObjectParameter("P_PUBLISHER_NAME", p_PUBLISHER_NAME) :
                new ObjectParameter("P_PUBLISHER_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_PUBLISHER", p_PUBLISHER_NAMEParameter, v_OUT);
        }
    
        public virtual ObjectResult<P_GET_ISSUE_Result> P_GET_ISSUE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_GET_ISSUE_Result>("P_GET_ISSUE");
        }
    
        public virtual int P_ISSUE(string p_STUDENT_NAME, Nullable<int> p_SEMESTER, string p_BOOK_NAME, string p_ISSUE_NAME, string p_RETURN_DATE, ObjectParameter v_OUT)
        {
            var p_STUDENT_NAMEParameter = p_STUDENT_NAME != null ?
                new ObjectParameter("P_STUDENT_NAME", p_STUDENT_NAME) :
                new ObjectParameter("P_STUDENT_NAME", typeof(string));
    
            var p_SEMESTERParameter = p_SEMESTER.HasValue ?
                new ObjectParameter("P_SEMESTER", p_SEMESTER) :
                new ObjectParameter("P_SEMESTER", typeof(int));
    
            var p_BOOK_NAMEParameter = p_BOOK_NAME != null ?
                new ObjectParameter("P_BOOK_NAME", p_BOOK_NAME) :
                new ObjectParameter("P_BOOK_NAME", typeof(string));
    
            var p_ISSUE_NAMEParameter = p_ISSUE_NAME != null ?
                new ObjectParameter("P_ISSUE_NAME", p_ISSUE_NAME) :
                new ObjectParameter("P_ISSUE_NAME", typeof(string));
    
            var p_RETURN_DATEParameter = p_RETURN_DATE != null ?
                new ObjectParameter("P_RETURN_DATE", p_RETURN_DATE) :
                new ObjectParameter("P_RETURN_DATE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_ISSUE", p_STUDENT_NAMEParameter, p_SEMESTERParameter, p_BOOK_NAMEParameter, p_ISSUE_NAMEParameter, p_RETURN_DATEParameter, v_OUT);
        }
    
        public virtual int P_DELETE_REGISTER(Nullable<int> p_BOOK_ID, ObjectParameter v_OUT)
        {
            var p_BOOK_IDParameter = p_BOOK_ID.HasValue ?
                new ObjectParameter("P_BOOK_ID", p_BOOK_ID) :
                new ObjectParameter("P_BOOK_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_DELETE_REGISTER", p_BOOK_IDParameter, v_OUT);
        }
    
        public virtual int P_UPDATE_REGISTER(Nullable<int> p_BOOK_ID, string p_BOOK_NAME, string p_AUTHOR_NAME, string p_PUBLISHER_NAME, string p_EDITION, Nullable<int> p_SEMESTER, Nullable<int> p_NUMBER_OF_COPIES, string p_IMAGE, ObjectParameter v_OUT)
        {
            var p_BOOK_IDParameter = p_BOOK_ID.HasValue ?
                new ObjectParameter("P_BOOK_ID", p_BOOK_ID) :
                new ObjectParameter("P_BOOK_ID", typeof(int));
    
            var p_BOOK_NAMEParameter = p_BOOK_NAME != null ?
                new ObjectParameter("P_BOOK_NAME", p_BOOK_NAME) :
                new ObjectParameter("P_BOOK_NAME", typeof(string));
    
            var p_AUTHOR_NAMEParameter = p_AUTHOR_NAME != null ?
                new ObjectParameter("P_AUTHOR_NAME", p_AUTHOR_NAME) :
                new ObjectParameter("P_AUTHOR_NAME", typeof(string));
    
            var p_PUBLISHER_NAMEParameter = p_PUBLISHER_NAME != null ?
                new ObjectParameter("P_PUBLISHER_NAME", p_PUBLISHER_NAME) :
                new ObjectParameter("P_PUBLISHER_NAME", typeof(string));
    
            var p_EDITIONParameter = p_EDITION != null ?
                new ObjectParameter("P_EDITION", p_EDITION) :
                new ObjectParameter("P_EDITION", typeof(string));
    
            var p_SEMESTERParameter = p_SEMESTER.HasValue ?
                new ObjectParameter("P_SEMESTER", p_SEMESTER) :
                new ObjectParameter("P_SEMESTER", typeof(int));
    
            var p_NUMBER_OF_COPIESParameter = p_NUMBER_OF_COPIES.HasValue ?
                new ObjectParameter("P_NUMBER_OF_COPIES", p_NUMBER_OF_COPIES) :
                new ObjectParameter("P_NUMBER_OF_COPIES", typeof(int));
    
            var p_IMAGEParameter = p_IMAGE != null ?
                new ObjectParameter("P_IMAGE", p_IMAGE) :
                new ObjectParameter("P_IMAGE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_UPDATE_REGISTER", p_BOOK_IDParameter, p_BOOK_NAMEParameter, p_AUTHOR_NAMEParameter, p_PUBLISHER_NAMEParameter, p_EDITIONParameter, p_SEMESTERParameter, p_NUMBER_OF_COPIESParameter, p_IMAGEParameter, v_OUT);
        }
    }
}
