//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_COUNTBOOK
    {
        public int ID { get; set; }
        public int BOOK_ID { get; set; }
        public string BOOK_NAME { get; set; }
        public string TOTAL_COUNT { get; set; }
    }
}
