//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BREGISTER
    {
        public int BOOK_ID { get; set; }
        public string BOOK_NAME { get; set; }
        public string AUTHOR_NAME { get; set; }
        public string PUBLISHER_NAME { get; set; }
        public string EDITION { get; set; }
        public int SEMESTER { get; set; }
        public int NUMBER_OF_COPIES { get; set; }
        public string BOOK_STATUS { get; set; }
        public string IMAGE { get; set; }
    }
}
